/*

		gara - Javascript Toolkit
	===========================================================================

		Copyright (c) 2007 Thomas Gossmann

		Homepage:
			http://garathekit.org

		This library is free software;  you  can  redistribute  it  and/or
		modify  it  under  the  terms  of  the   GNU Lesser General Public
		License  as  published  by  the  Free Software Foundation;  either
		version 2.1 of the License, or (at your option) any later version.

		This library is distributed in  the hope  that it  will be useful,
		but WITHOUT ANY WARRANTY; without  even  the  implied  warranty of
		MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See  the  GNU
		Lesser General Public License for more details.

	===========================================================================
*/

"use strict";

gara.provide("gara.events.ControlListener");

/**
 * Classes which implement this interface provide methods that deal with the events 
 * that are generated by moving and resizing controls.
 * 
 * @description
 * After creating an instance of a class that implements this interface it can be 
 * added to a control using the <code>addControlListener</code> method and removed using 
 * the <code>removeControlListener</code> method. When a control is moved or resized, 
 * the appropriate method will be invoked.
 *  
 * @interface gara.events.ControlListener
 * @name gara.events.ControlListener
 * @class
 * 
 * TODO: Remove class in favor of interface
 */

gara.Class("gara.events.ControlListener", /** @lends gara.events.ControlListener# */ {

	/**
	 * Sent when the location (x, y) of a control changes 
	 * relative to its parent (or relative to the display, for Shells).  
	 *
	 * @param {Event} e an event containing information about the control move
	 * @returns {void}
	 */
	controlMoved : function () {},

	/**
	 * Sent when the size (width, height) of a control changes. 
	 *
	 * @param {Event} e an event containing information about the control resize
	 * @returns {void}
	 */
	controlResized : function () {}
});