/*

		gara - Javascript Toolkit
	===========================================================================

		Copyright (c) 2007 Thomas Gossmann

		Homepage:
			http://garathekit.org

		This library is free software;  you  can  redistribute  it  and/or
		modify  it  under  the  terms  of  the   GNU Lesser General Public
		License  as  published  by  the  Free Software Foundation;  either
		version 2.1 of the License, or (at your option) any later version.

		This library is distributed in  the hope  that it  will be useful,
		but WITHOUT ANY WARRANTY; without  even  the  implied  warranty of
		MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See  the  GNU
		Lesser General Public License for more details.

	===========================================================================
*/

"use strict";

gara.provide("gara.events.TabFolderListener");

/**
 * Classes which implement this interface provide methods that deal with the events that are generated by the TabFolder control. 
 * 
 * @description
 * After creating an instance of a class that implements this interface it can be added to a tabfolder 
 * using the <code>addTabFolderListener</code> method and removed using the 
 * <code>removeTabFolderListener</code> method. 
 * When the state of the tabfolder changes, the appropriate method will be invoked.
 * 
 * @interface gara.events.TabFolderListener
 * @name gara.events.TabFolderListener
 * @class
 * 
 * TODO: Remove class in favor of interface
 */

gara.Class("gara.events.TabFolderListener", /** @lends gara.events.TabFolderListener# */ {

	/**
	 * Sent when the user clicks on the close button of an item in the TabFolder. 
	 * 
	 * @param e {Event} an event containing information about the close
	 * @returns {boolean} Indicating whether this operation should be allowed
	 */
	close : function (e) {}
});