/*	$Id: FocusListener.interface.js 91 2007-12-09 18:58:43Z tgossmann $

		gara - Javascript Toolkit
	===========================================================================

		Copyright (c) 2007 Thomas Gossmann

		Homepage:
			http://gara.creative2.net

		This library is free software;  you  can  redistribute  it  and/or
		modify  it  under  the  terms  of  the   GNU Lesser General Public
		License  as  published  by  the  Free Software Foundation;  either
		version 2.1 of the License, or (at your option) any later version.

		This library is distributed in  the hope  that it  will be useful,
		but WITHOUT ANY WARRANTY; without  even  the  implied  warranty of
		MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See  the  GNU
		Lesser General Public License for more details.

	===========================================================================
*/

gara.provide("gara.jswt.events.ControlListener");

/**
 * @interface ControlListener
 * @summary
 * Classes which implement this interface provide methods that deal with the events 
 * that are generated by moving and resizing controls.
 * 
 * @description
 * After creating an instance of a class that implements this interface it can be 
 * added to a control using the <code>addControlListener</code> method and removed using 
 * the <code>removeControlListener</code> method. When a control is moved or resized, 
 * the appropriate method will be invoked.
 *  
 * @namespace gara.jswt.events
 */

gara.Class("gara.jswt.events.ControlListener", {

	/**
	 * @method
	 * Sent when the location (x, y) of a control changes 
	 * relative to its parent (or relative to the display, for Shells).  
	 *
	 * @param {Event} e an event containing information about the mouse move
	 * @return {void}
	 */
	controlMoved : function() {},

	/**
	 * @method
	 * Sent when the size (width, height) of a control changes. 
	 *
	 * @param {Event} e an event containing information about the mouse move
	 * @return {void}
	 */
	controlResized : function() {}
});